### ISSUE TITLE
AlgoliaSearch v1.9.1 error on IE11

### ISSUE THREAD

**Issue by BanyuUrip** [algolia/algoliasearch-magento-2#677]
**Do you want to request a *feature* or report a *bug*?**
_Bug._
Steps to reproduce:

- Open https://magento2.algolia.com/women/tops-women/jackets-women.html on IE 11 

**Bug: What is the current behavior?**

![magento2_algoliasearch_v191_error_ie11](https://user-images.githubusercontent.com/6737571/52693500-79b64180-2f99-11e9-87dd-b234c69eabd8.jpg)

**Bug: What is the expected behavior?**
Product list page showed properly.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Algolia v1.9.1 for Magento 2

**Comment by JanPetr** [comment]
Hello @BanyuUrip, thank you for the report! 
It was fixed in the PR^. Feel free to give it a try 🙌

**Comment by BanyuUrip** [comment]
Hi @JanPetr,

Thank you for the reply.

I have tried the PR but still had a problem with the https://github.com/algolia/algoliasearch-magento-2/pull/678/commits/1da9d8f641225b8287d6abdb59a249916e2bc3ea. When I applied the line code below, the product list page still doesn't work including on Chrome and Firefox.

`<script src="//polyfill.io/v3/polyfill.min.js?features=default%2CArray.prototype.includes%2CPromise" src_type="url" crossorigin/>`

So I try to add "anonymous" to crossorigin attribute, and it works fine now (Chrome, Firefox and IE11).

`<script src="//polyfill.io/v3/polyfill.min.js?features=default%2CArray.prototype.includes%2CPromise" src_type="url" crossorigin="anonymous"/>`

Thanks
